name: Build Minecraft Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Klonování repozitáře
      uses: actions/checkout@v4

    - name: Nastavení JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Sestavení projektu pomocí Mavenu
      run: mvn clean package

    - name: Uložení vytvořeného JAR souboru
      uses: actions/upload-artifact@v4
      with:
        name: SimpleDoubleJump-Plugin
        path: target/*.jar
